version: '3'

services:
  orochi-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
