services:
  # Angular Dashboard Integration
  angular_dashboard:
    container_name: angular_dashboard
    image: ghcr.io/prabaljainn/orochi-ui:sha-ead43a1
    restart: always
    environment:
      BOX: 'true'                    # Enable PREFIX mode
      PREFIX: 'orochi'               # Set your PREFIX (or any custom name)
      # Connect to CVAT API through internal network
      CVAT_API_URL: "http://cvat_server:8080/api"
      CVAT_HOST: "${CVAT_HOST:-localhost}"
    labels:
      traefik.enable: "true"
      traefik.http.services.angular-dashboard.loadbalancer.server.port: "80"
      # ---- Middlewares ----

      # (Optional) CORS (camelCase keys)
      traefik.http.middlewares.dashboard-cors.headers.accessControlAllowMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      traefik.http.middlewares.dashboard-cors.headers.accessControlAllowHeaders: "Content-Type,Authorization,X-CSRFToken,X-Requested-With,Cookie"
      traefik.http.middlewares.dashboard-cors.headers.accessControlAllowCredentials: "true"
      traefik.http.middlewares.dashboard-cors.headers.accessControlMaxAge: "86400"
      traefik.http.middlewares.dashboard-cors.headers.accessControlAllowOriginList: "https://${CVAT_HOST:-localhost}"

      # Security headers to prevent mixed content and enforce HTTPS
      traefik.http.middlewares.dashboard-security.headers.contentSecurityPolicy: "upgrade-insecure-requests; default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https: wss:; font-src 'self' https:; object-src 'self' https:; media-src 'self' https:; frame-src 'self' https:;"
      traefik.http.middlewares.dashboard-security.headers.stsSeconds: "31536000"
      traefik.http.middlewares.dashboard-security.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.dashboard-security.headers.stsPreload: "true"
      traefik.http.middlewares.dashboard-security.headers.forceSTSHeader: "true"
      traefik.http.middlewares.dashboard-security.headers.referrerPolicy: "strict-origin-when-cross-origin"
      traefik.http.middlewares.dashboard-security.headers.customRequestHeaders.X-Forwarded-Proto: "https"
      traefik.http.middlewares.dashboard-security.headers.customRequestHeaders.X-Forwarded-Port: "443"
      traefik.http.middlewares.dashboard-security.headers.customRequestHeaders.X-Forwarded-Ssl: "on"

      # Path-based routing for PREFIX/dashboard paths and legacy language paths
      # HTTP to HTTPS redirect - UPDATE PATHS TO INCLUDE PREFIX
      traefik.http.routers.angular-dashboard-http.rule: Host(`${CVAT_HOST:-localhost}`) && (PathPrefix(`/orochi/dashboard`) || PathPrefix(`/orochi/api`) || PathPrefix(`/dashboard`) || (PathPrefix(`/en`) && !PathPrefix(`/api/`)) || (PathPrefix(`/ja`) && !PathPrefix(`/api/`)) || (PathPrefix(`/hi`) && !PathPrefix(`/api/`)) || (PathPrefix(`/ar`) && !PathPrefix(`/api/`)) || (PathPrefix(`/es`) && !PathPrefix(`/api/`)) || (PathPrefix(`/te`) && !PathPrefix(`/api/`)))
      traefik.http.routers.angular-dashboard-http.entrypoints: web
      traefik.http.routers.angular-dashboard-http.middlewares: "dashboard-https-redirect"
      traefik.http.routers.angular-dashboard-http.priority: "2000"

      # HTTPS redirect middleware
      traefik.http.middlewares.dashboard-https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.dashboard-https-redirect.redirectscheme.permanent: "true"

      # HTTPS routes for PREFIX/dashboard paths and legacy language paths
      traefik.http.routers.angular-dashboard-https.rule: Host(`${CVAT_HOST:-localhost}`) && (PathPrefix(`/orochi/dashboard`) || PathPrefix(`/orochi/api`) || PathPrefix(`/dashboard`) || (PathPrefix(`/en`) && !PathPrefix(`/api/`)) || (PathPrefix(`/ja`) && !PathPrefix(`/api/`)) || (PathPrefix(`/hi`) && !PathPrefix(`/api/`)) || (PathPrefix(`/ar`) && !PathPrefix(`/api/`)) || (PathPrefix(`/es`) && !PathPrefix(`/api/`)) || (PathPrefix(`/te`) && !PathPrefix(`/api/`)))
      traefik.http.routers.angular-dashboard-https.entrypoints: websecure
      traefik.http.routers.angular-dashboard-https.tls: "true"
      traefik.http.routers.angular-dashboard-https.tls.certresolver: lets-encrypt
      traefik.http.routers.angular-dashboard-https.middlewares: "dashboard-cors,dashboard-security"
      traefik.http.routers.angular-dashboard-https.priority: "2000"

    # REMOVE the custom nginx config mount - let the container handle it
    # volumes:
    #   - ./nginx-conf-custom/nginx-orochi.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cvat
    depends_on:
      - cvat_server
    # Add resource limits to prevent OOM kills
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
