FROM node:20

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application
COPY . .

# Expose port 4200 for Angular dev server
EXPOSE 4200

# Start Angular development server
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
