apiVersion: apps/v1
kind: Deployment
metadata:
  name: orochi-ui
  labels:
    app: orochi-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orochi-ui
  template:
    metadata:
      labels:
        app: orochi-ui
    spec:
      containers:
      - name: orochi-ui
        image: ${DOCKER_REGISTRY}/orochi-ui:${TAG}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orochi-ui-service
  labels:
    app: orochi-ui
spec:
  selector:
    app: orochi-ui
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orochi-ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: orochi-ui.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orochi-ui-service
            port:
              number: 80
